version: '3'
services:
  nginx:
    ports:
      - "3000:80"
  spenny:
    build: 
      context: .
      args: 
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev